### PR TITLE
Removing Deprecation Warnings

### PR DESCRIPTION
**Pull request by SillyInventor**
Add on_delete for foreign keys and one to one -- without on_delete now deprecated
Switch to MIDDLEWARE from MIDDLEWARE_CLASSES -- MIDDLEWARE_CLASSES deprecated
Switch 'urlresolvers import reverse' to 'urls import reverse' -- urlresolvers deprecated
Switch include(admin...) to just URLs -- Include() now requires namespace argument

### CODE REVIEW

**Comment by SillyInventor** [comment]
Added a commit to fix two warnings we were getting:
In use on the site: null has no effect on ManyToManyField.
In building django_teams alone: The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.

**Review by chathaway-codes — CHANGES_REQUESTED** [review]
Please bump the version in setup.py (-> 1.1.2) and update the Django version in libraries.txt to >= 1.9.

Please check that this works with Django 1.9 (I'll verify if it works, but if there are more changes please make them first)

**Comment by SillyInventor** [comment]
Should work with 1.9, sorry for not checking that earlier.

**Comment by SillyInventor** [comment]
Poke.

**Pull request merged**
